import React, { useState, useEffect, useMemo } from 'react';
import { HashRouter, Routes, Route, Link, NavLink, useNavigate, Navigate, useLocation, useParams } from 'react-router-dom';
import { ToastContainer, toast, TypeOptions } from 'react-toastify';
import { User, UserRole, Produce, Contract, ContractStatus } from './types';
import { useAuth } from './contexts/AuthContext';
import { useData } from './contexts/DataContext';

// ICONS
const HomeIcon = ({ className }: { className?: string }) => <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" className={className}><path d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z" /></svg>;
const Spinner = () => <div className="spinner-overlay"><div className="spinner"/></div>;

// DASHBOARD
const Dashboard = () => { const { user, logout } = useAuth(); const { produce:produces, contracts } = useData(); return (<div className="dashboard"><header><h1>Hello, {user?.name}</h1><button onClick={logout} className="logout-button">Logout</button></header><main><section className="summary"><div className="card"><h2>Total Produces</h2><p>{produces.length}</p></div><div className="card"><h2>Total Contracts</h2><p>{contracts.length}</p></div></section><section className="recent-activity"><h2>Recent Activity</h2></section></main></div>); };

// VERIFY LOGIN
const VerifyLogin = () => { const navigate=useNavigate(); const { verifyCode, login } = useAuth() as any; const location=useLocation(); const [code,setCode]=useState(''); const [loading,setLoading]=useState(false); const email=(location.state as any)?.email; if(!email) return <Navigate to="/login"/>; const submit=async(e:React.FormEvent)=>{ e.preventDefault(); setLoading(true); const { success } = await verifyCode(email, code); if(success){ toast.success('Login successful!'); navigate('/'); } setLoading(false); }; const resend=async()=>{ setLoading(true); await login(email); setLoading(false); }; return (<div className="auth-page"><form onSubmit={submit} className="auth-form"><h2>Verify Login</h2><p>Code sent to <strong>{email}</strong></p><div className="form-group"><label>Verification Code</label><input value={code} onChange={e=>setCode(e.target.value)} required/></div><button type="submit" disabled={loading} className="primary-button">{loading? 'Verifying...':'Verify & Login'}</button><div className="auth-links"><button type="button" onClick={resend} disabled={loading} className="link-button">Resend Code</button><Link to="/login">Back to Login</Link></div></form></div>); };

// REGISTER
const Register = () => { const navigate=useNavigate(); const { registerWithPassword } = useAuth(); const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [role,setRole]=useState<UserRole>(UserRole.FARMER); const [password,setPassword]=useState(''); const [confirm,setConfirm]=useState(''); const [loading,setLoading]=useState(false); const submit=async(e:React.FormEvent)=>{ e.preventDefault(); if(password!==confirm){ toast.error('Passwords do not match'); return;} setLoading(true); try { await registerWithPassword({ name,email,role }, password); navigate('/login',{ state:{ message:'Registration successful! Confirm email then login.'}}); } finally { setLoading(false);} }; return (<div className="auth-page"><form onSubmit={submit} className="auth-form"><h2>Create Account</h2><div className="form-group"><label>Name</label><input value={name} onChange={e=>setName(e.target.value)} required/></div><div className="form-group"><label>Email</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></div><div className="form-group"><label>Role</label><select value={role} onChange={e=>setRole(e.target.value as UserRole)}><option value={UserRole.FARMER}>Farmer</option><option value={UserRole.VENDOR}>Vendor</option><option value={UserRole.ADMIN}>Admin</option></select></div><div className="form-group"><label>Password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></div><div className="form-group"><label>Confirm Password</label><input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} required/></div><button type="submit" disabled={loading} className="primary-button">{loading? 'Registering...':'Register'}</button><div className="auth-links"><Link to="/login">Already have an account? Login</Link></div></form></div>); };

// LOGIN
const Login = () => { const navigate=useNavigate(); const { login, loginWithPassword, authError } = useAuth() as any; const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [mode,setMode]=useState<'otp'|'password'>('otp'); const [loading,setLoading]=useState(false); const location=useLocation(); const message=(location.state as any)?.message; useEffect(()=>{ if(message) toast.info(message); },[message]); const submit=async(e:React.FormEvent)=>{ e.preventDefault(); setLoading(true); let success=false; if(mode==='otp'){ const { result } = await login(email); success=!!result; if(success) navigate('/verify-login',{ state:{ email } }); else toast.error('Failed OTP login'); } else { const { success:pwdSuccess } = await loginWithPassword(email,password); success=pwdSuccess; if(success) navigate('/'); else toast.error('Failed password login'); } setLoading(false); }; return (<div className="auth-page"><form onSubmit={submit} className="auth-form"><h2>Login</h2>{authError && <div className="form-error">{authError}</div>}<div className="auth-mode-switcher"><button type="button" onClick={()=>setMode('otp')} className={mode==='otp'? 'active':''}>Use Email Code</button><button type="button" onClick={()=>setMode('password')} className={mode==='password'? 'active':''}>Use Password</button></div><div className="form-group"><label>Email</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></div>{mode==='password' && <div className="form-group"><label>Password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></div>}{mode==='otp' && <div className="form-group"><label>OTP</label><input value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter OTP" required/></div>}<button type="submit" disabled={loading} className="primary-button">{loading? 'Logging in...':'Login'}</button><div className="auth-links"><Link to="/register">Create an account</Link></div></form></div>); };

// APP
const App = () => { const { user, loadingAuth } = useAuth(); if(loadingAuth) return <Spinner/>; return (<div className="app-container"><HashRouter><ToastContainer position="top-right" autoClose={5000} hideProgressBar={false} newestOnTop={false} closeOnClick rtl={false} pauseOnFocusLoss draggable pauseOnHover /><Routes><Route path="/" element={user? <Dashboard/>:<Navigate to="/login"/>}/><Route path="/login" element={<Login/>}/><Route path="/register" element={<Register/>}/><Route path="/verify-login" element={<VerifyLogin/>}/><Route path="*" element={<Navigate to="/"/>}/></Routes></HashRouter></div>); };

export default App;
